In [1]:
def sum_num(x, y, z):
    return x + y + z

In [2]:
sum_num(1, 2, 3)

6

In [3]:
def sum_num(x, y, z = None): 
    return x + y + z

In [4]:
sum_num(1, 2)

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [5]:
def sum_num(x, y, z = None): 
    if z == None:
        return x + y
    else:
        return x + y + z

In [6]:
print(sum_num(1, 2, 3))
print(sum_num(1, 2))

6
3


In [7]:
x = [1, 2, 3, 4]

In [8]:
for item in x:
    print(item)

1
2
3
4


In [9]:
y = ('shubh', 4, 'shu', 5)

In [10]:
print(y)

('shubh', 4, 'shu', 5)


In [11]:
for item in y:
    print(item)

shubh
4
shu
5


In [12]:
y + ('s', 6)

('shubh', 4, 'shu', 5, 's', 6)

In [13]:
z = {'shu':'mish', 'lalu':'mama'}

In [14]:
for item in z.values():
    print(item)

mish
mama


In [15]:
m, n = z

In [16]:
m

'shu'

In [17]:
n

'lalu'

In [18]:
x = 'alli re aali maja tujheila'
x.split(' ')[-2]

'maja'

In [19]:
sf = {'name':'shubh', 'height':6}
statement = 'I am {} and I am {} feet tall'
print(statement.format(sf['name'], sf['height']))

I am shubh and I am 6 feet tall


In [20]:
import csv
%precision 2

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))

In [21]:
mpg[:3]

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv',

In [22]:
len(mpg)

234

In [23]:
mpg[0].keys()

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [24]:
sum(float(i['cty']) for i in mpg) / len(mpg)

16.86

In [25]:
sum(float(i['hwy']) for i in mpg) / len(mpg)

23.44

In [26]:
cylinder = set(i['cyl'] for i in mpg)
cylinder

{'4', '5', '6', '8'}

In [27]:
list = []

for c in cylinder:
    sum = 0
    count = 0
    for i in mpg:
        if i['cyl'] == c:
            sum += float(i['cty'])
            count += 1
    list.append((c, sum/count))
    
list.sort(key = lambda x: x[0])
list

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

In [28]:
class1 = set(i['class'] for i in mpg)
class1

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

In [29]:
list = []

for c in class1:
    sum = 0
    count = 0
    for i in mpg:
        if i['class'] == c:
            sum += float(i['cty'])
            count += 1
    list.append((c, sum/count))
    
list.sort(key = lambda x: x[1])
list

[('pickup', 13.00),
 ('suv', 13.50),
 ('2seater', 15.40),
 ('minivan', 15.82),
 ('midsize', 18.76),
 ('compact', 20.13),
 ('subcompact', 20.37)]

In [30]:
import datetime as dt
import time as tm

In [31]:
tm.time()

1658212047.36

In [32]:
x = dt.datetime.fromtimestamp(tm.time())
x

datetime.datetime(2022, 7, 19, 11, 57, 27, 453823)

In [33]:
x.year, x.hour

(2022, 11)

In [34]:
delta = dt.timedelta(days = 3)

In [35]:
dt.date.today() - delta

datetime.date(2022, 7, 16)

In [36]:
class Person:
    department = 'DESE' #a class variable

    def set_name(self, new_name): #a method
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [37]:
p = Person()
p.set_name('shubh')
p.set_location('bsp')
print('{} is {} boy and studies in {}'.format(p.name, p.location, p.department))

shubh is bsp boy and studies in DESE


In [38]:
s1 = [1, 9, 3, 4]
s2 = [2, 3, 4 ,5]
x = map(min, s1, s2)
x

In [39]:
for i in x:
    print(i)

1
3
3
4


In [40]:
list1 = ['1 2 3', '5 6 7']
def try2(list1):
    f = list1.split(' ')[0]
    l = list1.split(' ')[-1]
    return '{} {}'.format(f, l)
list2 = (map(try2, list1))
for i in list2:
    print(i)

1 3
5 7


In [41]:
import numpy as np

In [42]:
list1 = [1, 2, 3]
x = np.array(list)
x

array([['pickup', '13.0'],
       ['suv', '13.5'],
       ['2seater', '15.4'],
       ['minivan', '15.818181818181818'],
       ['midsize', '18.75609756097561'],
       ['compact', '20.127659574468087'],
       ['subcompact', '20.37142857142857']], dtype='<U18')

In [43]:
y = np.array([[1,2,3], [4,5,6]])
y

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
y.shape

(2, 3)

In [45]:
n = np.arange(0,11,2)
n

array([ 0,  2,  4,  6,  8, 10])

In [46]:
n.reshape(2,3)

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [47]:
n = np.linspace(0,11,6)
n

array([ 0. ,  2.2,  4.4,  6.6,  8.8, 11. ])

In [48]:
n.resize(2,3)
n

array([[ 0. ,  2.2,  4.4],
       [ 6.6,  8.8, 11. ]])

In [49]:
n = np.ones(5,int)
n

array([1, 1, 1, 1, 1])

In [50]:
n = np.ones([2,3],int)
n

array([[1, 1, 1],
       [1, 1, 1]])

In [51]:
m = np.vstack([n, 3*n])
m.shape

(4, 3)

In [52]:
(m.T).shape

(3, 4)

In [53]:
m = np.array([1,2,3,4,5,6,7,34,34,21,341231,1234,341,3])
m.max()
m.min()
m.mean()
m.std()
m.argmax()

10

In [54]:
r = np.arange(0,36,2)
r.resize((6, 6))
r

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22],
       [24, 26, 28, 30, 32, 34],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [55]:
r[r>30]

array([32, 34])

In [56]:
m = r[:2, :2]
m[:] = 0

In [57]:
r

array([[ 0,  0,  4,  6,  8, 10],
       [ 0,  0, 16, 18, 20, 22],
       [24, 26, 28, 30, 32, 34],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [58]:
m = r.copy()

In [59]:
m[:] = 10

In [60]:
r

array([[ 0,  0,  4,  6,  8, 10],
       [ 0,  0, 16, 18, 20, 22],
       [24, 26, 28, 30, 32, 34],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [61]:
m = np.random.randint(0,100,(5,5))
m

array([[61, 66, 81, 53, 83],
       [90, 33, 48, 22, 41],
       [15, 41, 16, 77, 59],
       [ 2, 93, 93, 55, 10],
       [38, 86, 12, 86, 32]])

In [62]:
for row in m:
    print(row)

[61 66 81 53 83]
[90 33 48 22 41]
[15 41 16 77 59]
[ 2 93 93 55 10]
[38 86 12 86 32]


In [63]:
len(m)

5

In [64]:
for i in range(len(m)):
    print (m[i])

[61 66 81 53 83]
[90 33 48 22 41]
[15 41 16 77 59]
[ 2 93 93 55 10]
[38 86 12 86 32]


In [65]:
for i, j in enumerate(m):
    print(i,' ',j)

0   [61 66 81 53 83]
1   [90 33 48 22 41]
2   [15 41 16 77 59]
3   [ 2 93 93 55 10]
4   [38 86 12 86 32]


In [66]:
n = m**2
for i,j in zip(m,n):
    print(i, ' ',j)

[61 66 81 53 83]   [3721 4356 6561 2809 6889]
[90 33 48 22 41]   [8100 1089 2304  484 1681]
[15 41 16 77 59]   [ 225 1681  256 5929 3481]
[ 2 93 93 55 10]   [   4 8649 8649 3025  100]
[38 86 12 86 32]   [1444 7396  144 7396 1024]
